# Generated by Django 3.1 on 2020-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='include_travelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbookings',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
