# Generated by Django 3.1 on 2020-09-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_remove_package_bookings'),
        ('users', '0002_auto_20200906_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookings',
        ),
    ]
