# Generated by Django 3.1 on 2020-09-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminside', '0006_remove_package_bookings'),
        ('users', '0003_delete_userbookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_adults', models.PositiveIntegerField(default=1)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('include_travelling', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
