# Generated by Django 3.1 on 2020-09-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
