# Generated by Django 3.1 on 2020-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userbookings_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookings',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
