# Generated by Django 3.1 on 2020-09-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_remove_package_bookings'),
        ('users', '0007_auto_20200907_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookings',
        ),
    ]
