# Generated by Django 3.1 on 2020-08-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_description', models.TextField()),
                ('price_per_room', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dtn_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('itinerary_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_person', models.PositiveIntegerField()),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('travelling_mode', models.CharField(choices=[('TN', 'Train'), ('FT', 'Flight'), ('BS', 'Bus')], default='FT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.IntegerField()),
                ('child_price', models.IntegerField()),
                ('inclusive', models.TextField()),
                ('exclusive', models.TextField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('accomodation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.accomodation')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.destination')),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.itinerary')),
                ('travel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.travel')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.destination')),
            ],
        ),
    ]
