# Generated by Django 3.1 on 2020-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationimages',
            name='image_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
