# Generated by Django 3.1 on 2020-09-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_destinationimages_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.travel'),
        ),
    ]
