# Generated by Django 3.1 on 2020-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_auto_20200822_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
        migrations.AlterField(
            model_name='travel',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
