# Generated by Django 3.1 on 2020-08-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_auto_20200822_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='itinerary_description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.package'),
        ),
        migrations.AddField(
            model_name='package',
            name='number_of_times_booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='accomodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.accomodation'),
        ),
        migrations.CreateModel(
            name='ItineraryDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('itinerary_description', models.TextField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.itinerary')),
            ],
        ),
    ]
