# Generated by Django 3.1 on 2020-09-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_auto_20200906_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarydescription',
            options={'ordering': ['day_number']},
        ),
    ]
