# Generated by Django 3.1 on 2020-09-06 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('adminside', '0004_auto_20200906_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bookings',
            field=models.ManyToManyField(through='users.UserBookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminside.package'),
        ),
    ]
