# Generated by Django 3.1 on 2020-09-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_auto_20200906_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='bookings',
        ),
    ]
