# Generated by Django 3.1 on 2020-09-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_package_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='bookings',
        ),
    ]
