# Generated by Django 3.1 on 2020-09-07 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_userbookings'),
        ('adminside', '0008_remove_package_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bookings',
            field=models.ManyToManyField(through='users.UserBookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
